variables:
  DOCUMENT: docs/JOSS/paper.md

stages:
  - convert

md-to-pdf:
  stage: convert
  tags:
    - inara
  image:
    name: openjournals/inara
    entrypoint: ["docs/JOSS/"]
  script:
    - docs/JOSS/make pdf ARTICLE=docs/JOSS/paper.md
  artifacts:
    paths:
      - docs/JOSS/
