variables:
  DOCUMENT: docs/JOSS/paper.md

stages:
  - convert

md-to-pdf:
  stage: convert
  tags:
    - inara
  image:
    name: openjournals/inara
    entrypoint: [""]
  script:
    - inara -p -o pdf ${DOCUMENT}
  artifacts:
    paths:
      - docs/JOSS/${DOCUMENT%.md}.pdf
