variables:
  DOCUMENT: docs/JOSS/paper.md

stages:
  - convert

md-to-pdf:
  stage: convert
  tags:
    - inara
  image:
    name: openjournals/inara
    entrypoint: ["docs/JOSS/"]
  script:
    - make pdf ARTICLE=$DOCUMENT TARGET_FOLDER=docs/JOSS/
  artifacts:
    paths:
      - ${DOCUMENT%.md}.pdf

