variables:
  DOCUMENT: docs/JOSS/paper.md

stages:
  - convert

md-to-pdf:
  stage: convert
  tags:
    - inara
  image:
    name: openjournals/inara
    entrypoint: [""]
  script:
    - make pdf ARTICLE=/my/path/paper.md
  artifacts:
    paths:
      - docs/JOSS/
