FROM debian:stable-slim

RUN apt update && \
apt-get install -y \
chromium \
cmake \
g++ \
gfortran \
git \
libblas-dev \
liblapack-dev \
libopenmpi-dev \
pkg-config \
python3 \
python3-build \
python3-pip \
python3-venv \
twine
